name: Bump package in dependent repos on releases

on:
  release:
    types:
      - published

jobs:

  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bumping
        uses: derberg/npm-dependency-manager-for-your-github-org@50475c0f121fd00511720c5040b45f1e1e10a596
        with:
          custom_id: "dependency update from asyncapi bot"
          github_token: ${{ secrets.CUSTOM_TOKEN }}
          repos_to_ignore: "piontek"
          committer_username: pomidor
          committer_email: pomidor@pomidor.com
          packagejson_path: ./gleboko
          base_branch: dupa
