name: Bump package in dependent repos on releases

on:
  release:
    types:
      - published

jobs:

  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bumping
        uses: derberg/custom-dependabot-for-your-github-org@1ee3765097e16ec73fc60002afe3547f60c08da2
        with:
          github_token: ${{ secrets.CUSTOM_TOKEN }}
          repos_to_ignore: "piontek"
          committer_username: pomidor
          committer_email: pomidor@pomidor.com
